### PR TITLE
:arrow_up: Upgrading app to use latest versions in 2023

### PR DESCRIPTION
**Pull request by vcampitelli**
I created a new project using `flutter create` and merged the changes so we can use the latest SDK and dependencies versions.

### CODE REVIEW

**Comment by mooreds** [comment]
Hmmm. Why not create a new project? Is there a reason to upgrade? Sometimes upgrades can get hairy, and we can:

* create a new project
* update the old project README to point to the new project
* archive the old project

pretty easily.

**Comment by vcampitelli** [comment]
IMHO for this specific case we don't need a new project because there weren't too many changes to be honest. For instance, 4 of the changed files are just to update comments. So I do think it's an easy upgrade.

**Comment by mooreds** [comment]
Sounds good, then.

**Review by mooreds — APPROVED** [review]
LGTM after a basic scan. Didn't build it out, assume you did so.

**Comment by vcampitelli** [comment]
@mooreds I have upgraded all dependencies to the latest versions available, made a few changes to reflect breaking changes and tested it out in Android Studio, so everything's working now.

My suggestion would be:
- Rename current branch from `master` to `v1` for instance
- Merge this PR into a new `master` branch

**Comment by mooreds** [comment]
@vcampitelli any reason to create the `v1`? We had some other folks try to build it and it didn't work,and it seems like you now have a working version. I'm included to merge it in as is.

**Pull request merged**
